export interface CatalogProduct {
  name: string; category: string; description: string; idealClient: string;
  targetRubros: string[]; problems: string[]; benefits: string[];
  price: string; objections: string[]; shortMessage: string; longMessage: string;
  salesPriority: string; commercialMargin: string; active: boolean;
}

export const OFFICIAL_CATALOG: CatalogProduct[] = [
  {
    name: 'ShelbyPOS',
    category: 'POS / Retail',
    description: 'Sistema punto de venta para tiendas, minimarkets, farmacias y negocios de retail. Control de inventario, caja y reportes en tiempo real.',
    idealClient: 'Dueño de tienda, almacén, farmacia o negocio de mostrador que vende productos físicos.',
    targetRubros: ['minimarket', 'tienda', 'almacén', 'abarrotes', 'farmacia', 'ferretería', 'ropa', 'calzado', 'supermercado', 'kiosco', 'retail'],
    problems: ['Control de inventario manual', 'Pérdida de dinero en caja', 'Sin reportes de ventas', 'Cierres de caja incorrectos', 'Merma no controlada'],
    benefits: ['Inventario en tiempo real', 'Cierre de caja automático', 'Reportes diarios de ventas', 'Control de merma', 'Lector de código de barras integrado'],
    price: 'Desde $299/mes',
    objections: ['Es muy caro', 'Ya tengo sistema', 'No tengo tiempo para aprender', 'Mi negocio es pequeño'],
    shortMessage: 'Controla tu tienda, elimina mermas y cierra la caja sin errores. ShelbyPOS desde $299/mes.',
    longMessage: 'ShelbyPOS es el sistema punto de venta para negocios latinoamericanos. Control de inventario en tiempo real, reportes automáticos y caja exacta. Instalación en 1 día, capacitación incluida, soporte por WhatsApp sin costo adicional.',
    salesPriority: 'alta',
    commercialMargin: '35%',
    active: true,
  },
  {
    name: 'ShelbyEats',
    category: 'Restaurantes',
    description: 'Sistema de gestión para restaurantes, cafeterías, bares y fondas. Comandas digitales, control de mesas y menú en QR.',
    idealClient: 'Dueño de restaurante, cafetería o bar con más de 3 mesas o servicio a domicilio.',
    targetRubros: ['restaurante', 'cafetería', 'café', 'bar', 'fast food', 'comida rápida', 'fonda', 'panadería', 'cocina'],
    problems: ['Pedidos en papel perdidos', 'Sin comunicación cocina-mesero', 'Cuentas incorrectas', 'Sin control de mesas', 'Sin saber qué platos son rentables'],
    benefits: ['Comanda digital a cocina', 'Menú QR para clientes', 'Control de mesas en tiempo real', 'Reportes de platos más vendidos', 'Funciona sin internet'],
    price: 'Desde $399/mes',
    objections: ['El personal no sabe usar tecnología', 'Mi restaurante es pequeño', 'Ya tengo caja registradora', 'Qué pasa si se cae internet'],
    shortMessage: 'Elimina comandas en papel, controla tus mesas y sabe qué platillos te dan más utilidad. ShelbyEats desde $399/mes.',
    longMessage: 'ShelbyEats digitaliza la operación de tu restaurante: comandas en tablet, menú QR para clientes, control de mesas y reportes de rentabilidad por platillo. Funciona offline. Instalación en 1 día, capacitación incluida.',
    salesPriority: 'alta',
    commercialMargin: '40%',
    active: true,
  },
  {
    name: 'MiComunidad360',
    category: 'Administración',
    description: 'Plataforma para administradoras de condominios, edificios y comunidades cerradas. Cobro digital de cuotas, control de acceso y comunicación con residentes.',
    idealClient: 'Administrador de condominio o edificio que gestiona cobros, acceso y comunicación con más de 20 unidades.',
    targetRubros: ['condominio', 'edificio', 'conjunto residencial', 'administradora', 'departamentos', 'fraccionamiento', 'conjunto habitacional'],
    problems: ['Cobro de cuotas manual y moroso', 'Sin control de visitas', 'Comunicación caótica con residentes', 'Sin transparencia en gastos comunes', 'Reportes financieros manuales'],
    benefits: ['Cobro digital con recordatorios automáticos', 'App para residentes', 'Control de acceso y visitas', 'Transparencia en gastos comunes', 'Estados de cuenta automáticos'],
    price: 'Desde $599/mes',
    objections: ['Los residentes no usan apps', 'Es muy caro para el presupuesto', 'Necesito autorización de la asamblea', 'Ya tenemos otro sistema'],
    shortMessage: 'Cobra cuotas digitalmente, controla accesos y mantén a tus residentes informados. MiComunidad360 desde $599/mes.',
    longMessage: 'MiComunidad360 digitaliza la administración de tu condominio: cobro de cuotas con recordatorios automáticos, control de visitas, comunicados a residentes y transparencia total en gastos comunes. App para residentes incluida. Ideal para 20+ unidades.',
    salesPriority: 'media',
    commercialMargin: '45%',
    active: true,
  },
  {
    name: 'Desarrollo Web',
    category: 'Marketing Digital',
    description: 'Diseño y desarrollo de páginas web profesionales, landing pages y tiendas online para negocios locales y pymes.',
    idealClient: 'Negocio local, profesional independiente o pyme sin presencia digital o con sitio web desactualizado.',
    targetRubros: ['pyme', 'negocio local', 'profesional', 'clínica', 'dentista', 'veterinaria', 'consultora', 'inmobiliaria', 'servicios', 'estética', 'salón', 'óptica'],
    problems: ['Sin presencia digital', 'Página web desactualizada', 'Sin tienda online', 'Clientes no los encuentran en Google', 'Sin integración con WhatsApp'],
    benefits: ['Web profesional y responsiva', 'Posicionamiento SEO en Google', 'Tienda online integrada', 'Botón WhatsApp y formulario de contacto', 'Google My Business configurado'],
    price: 'Desde $9,900 (proyecto único, sin mensualidades)',
    objections: ['Las redes sociales son suficientes', 'Ya tengo página en Facebook', 'Es muy caro', 'No tengo tiempo para dar contenido'],
    shortMessage: 'Tu negocio en internet, visible en Google y conectado a WhatsApp. Web profesional desde $9,900.',
    longMessage: 'Desarrollamos tu página web profesional y responsiva, optimizada para aparecer en Google. Incluye WhatsApp directo, formulario de contacto, galería de servicios y Google My Business. Entrega en 2 semanas, sin mensualidades. Tu negocio disponible 24/7.',
    salesPriority: 'alta',
    commercialMargin: '50%',
    active: true,
  },
  {
    name: 'Desarrollo de Apps',
    category: 'Apps',
    description: 'Desarrollo de aplicaciones móviles Android e iOS a medida. Canal digital propio sin comisiones de terceros.',
    idealClient: 'Negocio con delivery propio, servicio a domicilio o programa de fidelización que quiere canal directo con sus clientes.',
    targetRubros: ['delivery', 'servicio a domicilio', 'gimnasio', 'lavandería', 'servicio técnico', 'empresa mediana', 'franquicia', 'cadena', 'taller'],
    problems: ['Sin canal digital propio', 'Pagan comisiones a plataformas de delivery', 'Sin fidelización digital', 'Sin notificaciones push', 'Dependen de WhatsApp para pedidos'],
    benefits: ['App propia iOS y Android', 'Pedidos sin comisiones', 'Notificaciones push', 'Programa de lealtad', 'Panel de administración incluido'],
    price: 'Desde $29,900 (proyecto)',
    objections: ['Es muy caro', 'Cuánto tiempo tarda', 'Mis clientes no descargan apps', 'Ya tenemos WhatsApp Business'],
    shortMessage: 'Tu propia app móvil, sin comisiones y con tus clientes fidelizados. Apps desde $29,900.',
    longMessage: 'Desarrollamos tu app para Android e iOS con panel de administración. Pedidos directos sin comisiones, notificaciones push, programa de lealtad y geolocalización. Entrega en 6-8 semanas. Deja de pagar comisiones y ten a tus clientes en tu propio canal.',
    salesPriority: 'media',
    commercialMargin: '60%',
    active: true,
  },
  {
    name: 'Automatización con IA',
    category: 'IA / Automatización',
    description: 'Agentes de inteligencia artificial y automatizaciones para eliminar tareas repetitivas, mejorar respuestas y atender clientes 24/7.',
    idealClient: 'Empresa con procesos manuales repetitivos que pierde ventas por respuestas lentas o quiere atención 24/7 sin contratar más personal.',
    targetRubros: ['empresa', 'pyme mediana', 'servicio profesional', 'e-commerce', 'logística', 'seguros', 'inmobiliaria', 'hotel', 'agencia', 'clínica'],
    problems: ['Respuestas lentas a clientes en WhatsApp', 'Sin atención fuera de horario', 'Cotizaciones manuales que tardan días', 'Procesos administrativos repetitivos', 'Cuellos de botella en atención'],
    benefits: ['Chatbot WhatsApp 24/7', 'Cotizaciones automáticas en segundos', 'Respuestas instantáneas con IA', 'Ahorro de 20+ horas semanales', 'Integración con CRM y email'],
    price: 'Desde $1,499/mes',
    objections: ['La IA no puede reemplazar el trato humano', 'Mis clientes son difíciles de automatizar', 'No entendemos de tecnología', 'Costo muy alto'],
    shortMessage: 'Atiende clientes 24/7, automatiza cotizaciones y ahorra 20+ horas semanales. IA desde $1,499/mes.',
    longMessage: 'Implementamos agentes de IA para WhatsApp, email y web que atienden 24/7, responden preguntas frecuentes, generan cotizaciones automáticas y escalan a humanos cuando es necesario. No reemplazamos al equipo: liberamos su tiempo para lo que importa. Implementación en 2 semanas.',
    salesPriority: 'alta',
    commercialMargin: '55%',
    active: true,
  },
];
